# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application CI/CD

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Elke zondag om 00:00 (wekelijkse SAST scan)

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Run Static Application Security Testing (SAST)
    - name: Run SAST
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security-and-quality'

    # Check dependencies for vulnerabilities
    - name: Dependency check
      run: |
        pip install safety
        safety check

    # Check for secrets in the code
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown

    # Fail the pull request if there are any warnings or errors
    - name: Enforce security policies
      if: ${{ failure() }}
      run: |
        echo "Checks failed. Please resolve all warnings and errors before merging."
        exit 1

  weekly-sast:
    name: Weekly SAST Scan
    runs-on: ubuntu-latest
    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Run Static Application Security Testing (SAST)
    - name: Run SAST
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security-and-quality'
